FROM continuumio/anaconda3

# example call of docker RUN command see more at: https://docs.docker.com/engine/reference/builder/
RUN apt-get update --fix-missing && apt-get install -y g++ gcc

# need do the following
# clone spinning up
# install dependencies for spinning up
# install spinning up using pip